/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
reset;
model moes.mod;
include objective_TOTEX.mod;
#include objective_Emissions.mod;
data moes.dat;
/*---------------------------------------------------------------------------------------------------------------------------------------
Including all technologies files 
---------------------------------------------------------------------------------------------------------------------------------------*/ 
include moesSolar.mod;
include moesSolar.dat;

include moesSOFC.dat;

include moesboiler.dat;


include moesHP_R1270_MT.dat;
include moesHP_R1270_MT.mod;

include moesHP_R1270_LT.dat;
include moesHP_R1270_LT.mod;

include moesHP_R290_LT.dat;
include moesHP_R290_LT.mod;

include moesHP_R290_MT.dat;
include moesHP_R290_MT.mod;

/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver 'gurobi';                                         # choose the solver
option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns
option presolve 5e-05;
/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/

#display Qheating;
#display Qheatingdemand;

#display mult;
display mult_t;
#display use_t;
display use;
display Emissions;
display Totalcost;
display c_spec;


#display usedroofAreaSTC;
#display Edemand;

#display FlowOutUnit;


#display Flowin;
#display Flowout;

#display FlowInUnit;
#display FlowOutUnit;

#display Buildings;
