# Modelling of a heat pump and data reconciliation

```{r, echo=F, results='hide',label='activate venv'}
#path <- file.path('./venv/bin/python')
library(reticulate)
#use_python(path)
use_virtualenv('./venv', required=FALSE)
```

```{python, echo=F, results='hide', label='load data'}
import matplotlib
matplotlib.use('Agg')
import codes_01_energy_demand.NR_functions as fct1
import codes_03_HP_modeling.Regression_Mirco.carnot_regression as fct2
from codes_01_energy_demand.NR_functions import WeatherClustering
import numpy as np; from numpy import matlib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.cluster import KMeans, SpectralClustering, AgglomerativeClustering
import os
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display, HTML
import amplpy
from amplpy import AMPL, DataFrame
import sys
import re
import glob
```

## Degrees of Freedom (DOF) analysis

**Given:**

The VALI model of the 2-stage heat pump with tags set to OFF (the default working fluid is R290, you should not change it) – *R-290.bls*. 

A csv file with 5 combinations of sets, only one of which is correct.

**Task**

Perform a DOF analysis to identify which tags must be set to CST and which ones must remain OFF.

Activate the tags and make sure the model is running properly.

*Hint*: For each component, identify how many measurements are needed for mass and energy balances, how many measurements are set as parameters and how many are calculated by the model. 

**Result**

## Introduction

In order to perform a DOF analysis, the needed ingredients are necessary: 

- The state variables of the flows
- The balance equations, often being energy balance (EB), mass balance (MB), pressure drop (P) 
- The model/performances equations, describing how the unit act on an engineering perspective.

The state variables of the flows are characterized by a minimum number of state variables given by the Gibbs phase rule, i.e. for a stream of N compounds, N+2 variables are sufficient to fully characterize it, with at least one extensive variable. From that, all other properties can be derived, provided the right constitutive equations.

For this analysis, we'll consider the steady-state operation of the system.

## System DOF analysis

A simple preliminary analysis allows to determine the overall minimum DOF of the system, giving a lower bound of measurements necessary to make it solvable. Representing the system as a flowsheet allows to retrieve the number of variables and equations. The variables consists of all the material flows, the electricity flows and the heat flows, assuming that each material flows bring 3 variables. The equations are one mass balance and one energy balance per unit in the system, the isentropic efficiencies for both compressor as well as the isenthalpic expansions in the valves. Finally, having 9 flows, all of them having 1 phase, and 8 units yields:

$ n_s = n_v - n_e =  (27+4+2)- (8+8+2+2) = 13$

And thus $n_s = 13$, meaning that we need at least 13 specifications to characterize the whole system. 

### VALI tags propositions
For this exercise, we're provided with 5 sets of possible tag arrangement. To goal is to determine which one of those is possible based on the DOF analysis. As we can see in (@tbl-DOFprop), all arrangement meet the minimum measurement requirements. However, we're not certain that the local DOF is respected. Summing $n_s$ for each unit processs and substracting the link between them should allow to determine to total number of DOF of the system taking local DOF into account. Since all tag arrangement provide a different number of set points, the solution should be given by the arrangement with matching number of DOF.

|       | Option 1 | Option 2 | Option 3 | Option 4 | Option 5 |
|-------|----------|----------|----------|----------|----------|
|DOF    | 14       | 18       | 19       | 16       | 13       |
: Measurements of the possible arrangement {#tbl-DOFprop}

## Unit models

### Compressor
Stating the unit model for a single compressor with one inlet stream and one outlet stream yields:

| Type  | Variables                                      | #        |
|-------|------------------------------------------------|----------|
| $n_x$ | $(n_{in}+n_{out})*(n_c+2)$                     | 6        |
| $n_p$ | $\Delta P$                                     | 2        |
|       | $\dot{W}_{in}$                                 |          |
| $n_t$ | $\eta_{is}$                                    | 1        |
| $n_v$ |                                                | 9        |

| Type  | Equations                                      | #        |
|-------|------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                 | 1        |
| (EB)  | $\dot{W}_{in}= \dot{m}_{in}c_p(T_{out}-T_{in})$| 1        |
| (P)   | $\Delta P=cst$                                 | 1        |
| (M)   | $\dot{W}_{in} =\eta_{is}\dot{W}_{in,is}$       | 1        |
| $n_e$ |                                                | 4        |

And thus $n_s = n_x-n_e= 2$, meaning we need 5 specifications to characterize a compressor.

### Evaporator
For the evaporator, we proceed the same way. We model the heat exchange of the lake as a constant heat transfer, allowing to simplify the equation statement since only our main flow has to be considered. In the general case, the fluid enters the evaporator with a vapor quality $x_{in}<1$, but based on the assumption that the entering flow is purely gaseous allows to further simplify the modelisation. 

| Type  | Variables                                      | #        |
|-------|------------------------------------------------|----------|
| $n_x$ | $(n_{in}+n_{out})*(n_c+2)$                     | 6        |
| $n_p$ | $\Delta P$                                     | 1        |
|       | $\dot{Q}_{in}$                                 | 1        |
| $n_t$ | $\eta_{is}$                                    | 1        |
| $n_v$ |                                                | 9        |

| Type  | Equations                                        | #        |
|-------|--------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   | 1        |
| (EB)  | $\dot{Q}_{in}= \dot{m}_{in}c_p(T_{evap}-T_{in})$ | 1        |
| (P)   | $\Delta P=0$                                     | 1        |
| (M)   | $\dot{Q}_{in}= UA\cdot \text{LMTD}$              | 1        |
| $n_e$ |                                                  | 4        |

And thus $n_s = n_x-n_e= 2$, meaning we need 5 specifications to characterize a compressor.

### Condensor
The VALI model suggest to model the condensor in two part: one taking care of the change of temperature (sensible), the second one modelling the phase change (latent). Using the same logic as the evaporator, only the main flow is considered and the other flows are modeled as heat transfer. The unit model equation will be the same for both condensor, and only the heat transfer model will vary. The base variables are the following:

| Type  | Variables                                      | #        |
|-------|------------------------------------------------|----------|
| $n_x$ | $(n_{in}+n_{out})*(n_c+2)$                     | 6        |
| $n_p$ | $\Delta P$                                     | 1        |
|       | $\dot{Q}$                                      | 1        |
| $n_t$ |                                                | 0        |
| $n_v$ |                                                | 8        |

#### Sensible condensor
The model equation for the sensible condensor is to assume a constant pressure during the heat transfer:

| Type  | Equations                                        | #        |
|-------|--------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   | 1        |
| (EB)  | $\dot{Q}_{in}= \dot{m}_{in}c_p(T_{out}-T_{in})$  | 1        |
| (P)   | $\Delta P=0$                                     | 1        |
| (M)   | $\dot{Q}_{in}= UA\cdot \text{LMTD}$              | 1        |
| $n_e$ |                                                  | 4        |

And thus $n_s = n_x-n_e = 2$, meaning that we need 2 specifications to characterize the sensible condensor.

#### Latent condensor
The model equation for the latent condensor is to assume a constant temperature during the heat transfer:

| Type  | Equations                                        | #        |
|-------|--------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   | 1        |
| (EB)  | $\dot{Q}_{in}= \dot{m}_{in}\cdot L$              | 1        |
| (P)   | $\Delta P=0$                                     | 1        |
| (M)   | $\dot{Q}_{in}= UA\cdot \text{LMTD}$              | 1        |
| $n_e$ |                                                  | 4        |

And thus $n_s = n_x-n_e = 2$, meaning that we need 2 specifications to characterize the latent condensor.

### Expansion valve

Assuming the expansion valves are not going through a phase change allows to ignore the vapor quality for both valves. The model implies an isenthalpic pressure drop.

| Type  | Variables                                      | #        |
|-------|------------------------------------------------|----------|
| $n_x$ | $(n_{in}+n_{out})*(n_c+2)$                     | 6        |
| $n_p$ | $\Delta P$                                     | 1        |
| $n_t$ | -                                              | 0        |
| $n_v$ |                                                | 7        |

| Type  | Equations                                        | #        |
|-------|--------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   | 1        |
| (EB)  | $0 = \dot{m}_{in}c_p(T_{out}-T_{in})$            | 1        |
| (P)   | $\Delta P = cst$                                 | 1        |
| (M)   | $h_{in}=h_{out}$                                 | 1        |
| $n_e$ |                                                  | 4        |


And thus $n_s = n_v-n_e= 3$, meaning we need 3 specifications to characterize a pressure valve.


### Flash tank

The flash tank involves a little bit more of complexity due to the multiple flows mixing. 

| Type  | Variables                                      | #        |
|-------|------------------------------------------------|----------|
| $n_x$ | $(n_{in}+n_{out})*(n_c+2)$                     | 12       |
| $n_p$ | $\Delta P_1$                                   | 2        |
| $n_p$ | $\Delta P_2$                                   |          |
| $n_t$ | -                                              | 0        |
| $n_v$ |                                                | 14       |

| Type  | Equations                                        | #        |
|-------|--------------------------------------------------|----------|
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   | 2        |
| (MB)  | $\dot{m}_{in} = \dot{m}_{out}$                   |          |
| (EB)  | $0 = \dot{m}_{in}c_p(T_{out}-T_{in})$            | 1        |
| (P)   | $\Delta P_1 = 0$                                 | 2        |
| (P)   | $\Delta P_2 = 0$                                 |          |
| (M)   |                                                  |          |
| $n_e$ |                                                  | 5        |


And thus $n_s = n_x-n_e= 2$, meaning we need 5 specifications to characterize a flash tank.

## VALI Tags selection
Now that all the types of unit models are characterized, it should be possible to determine the minimum number of measurements needed to make the system fully determined. Summing all corresponding DOF with the number of units and substracting the links yields:



Working model of the 2-stage HP for the working fluid R290.

### Model adjustment to a second working fluid (Optional)

**Task**

Adjust the model from the previous section to a second working fluid of your choice between the 7 options listed in Table 4.1.

*Hints*:

- Modify the working fluid (Thermod) in your simulation file.
- Correct the pressure ratio of the compressors so that the high-pressure level corresponds to the saturation pressure for the desired condensation temperature.
- Adjust the flow rate so that the heat pump has a heating capacity of 6000 kW (the maximum capacity of the HP is in this magnitude).

**Result**

Working model of the 2-stage HP for the working fluid of your choice.

## Data reconciliation

**Given**

Measurements for 7 working fluids, each with 2 temperature levels (low-temperature and medium-temperature) and between 6 and 11 periods.

**Task**

Run the VALI model with the corresponding measurements.

**Result**

Obtain the reconciled files.

*Hint*:
Note that the measurement file indicates where the reconciled file should be saved. For instance, for the *R-290_LT_1.txt* file, the location is defined by the command `ARCHIVE -T Reconciled/reconc_R-290_LT_1.txt`. Make sure to have a folder named *Reconciled* in the same folder as the Vali model.

## Performance and cost evaluation

```{python, echo=F, eval=T,label= regression}


results, observed =fct2.get_reg()
#| label: weather cluster plotting
T_ext_span=np.linspace(0,25,100)
carnot_span=pd.DataFrame(index=T_ext_span)
colors=['blue','brown','green','red']

for j in results.index.values:
    carnot_span[j]=results.loc[j]['a']*np.power(T_ext_span,2)-results.loc[j]['b']*T_ext_span+results.loc[j]['c']

fig = px.line(carnot_span, x=carnot_span.index, y=carnot_span.columns, title='Carnot efficiency function of ambient temperature',labels={'index': 'Ambient temperature [°C]', 'value':'Carnot efficiency','variable': 'Fluids'},color_discrete_sequence=colors)

count=0
for j in results.index.values:
    fig.add_scatter(x=observed['T_ext_'+j],y=observed['Carnot_'+j],mode='markers',marker=dict(color=colors[count]),showlegend=False)
    count+=1

fig.add_scatter(x=[5],y=[0.5],mode='markers',marker=dict(color='black',opacity=0),name='Observed data')
fig.add_trace(go.Scatter(x=[5],y=[0.5],name='Regression',line=dict(color='black'),marker=dict(size=0,opacity=0)))
```

**Given**

Three AMPL files: *moes2021_P4_Rxxx.dat*, *moes2021_P4.mod* and *moes2021_P4.run*.

Table with ambient temperatures for each measurement.

**Task**

For the performance evaluation:

- Use the information in the reconciled files from VALI to complete the AMPL model.
- Derive a regression curve that calculates the Carnot factor as a polynomial function of the ambient temperature for both stages of the HP. You are asked to derive the factors *a*, *b* and *c*. In general, you can assume:

\begin{equation}
C_{Carnot}^*(t) = a \cdot T_{amb}^2(t) - b \cdot T_{amb}(t) + c
(\#eq:Carnot1)
\end{equation}

\begin{equation}
C_{Carnot} = \frac {Q(t)}{W(t)} \cdot \frac {T_{cond}(t)-T_{evap}(t)}{T_{cond}(t)}
(\#eq:Carnot2)
\end{equation}

- Make sure to identify the evaporator and the condenser temperature of both sides accordingly. You will find some hints in the AMPL code. Note that the temperatures in Eq. \@ref(eq:Carnot2) must be in K.

For the cost evaluation:

- Assume the worst case conditions to evaluate the area of the heat exchangers, which is then fixed, and to size the other components (e.g. compressors).
Calculate the cost for the two-stage HP with cost functions provided in the literature or taken from previous sections. Consider only the costs of the heat exchangers and the compressor, since they are the main contributors to the investment cost of heat pumps. 

**Result**

Polynomial function for the Carnot factor as a function of the ambient temperature Ta.

Size of the heat exchangers and compressor.

Cost of the total system.

Unit cost of the system per kW of heating capacity.
