# Conclusions

At the end of the project, the main recommendations and findings are reported.

The most important values are reported and presented in a synthetic (graphical and tabulated) way. The conclusions should include the key take-home messages with the key numbers associated. 


Keep in mind that the emissions considered are only from electricity and natural gas import. A more refined model may include emissions from technology installation. For example, all technologies not using imported electricity or natural gas will produce zero CO2 emissions. Therefore, technologies not relying on imports (such as PV) are artificially encouraged in all our scenarios optimizing emissions.


In many scenarios, the TOTEX increase is huge. It may be caused by the extreme cluster, i.e. the hour in the year where temperature and irradiation are at their lowest. This extreme cluster causes a large energy demand in a short period of time, i.e. a large heating power. This has the effect to require installation of certain technologies almost only for one hour in the year, and thus increasing the TOTEX drastically. The model used considers that heat must be balanced for each hour, avoiding comfort temperature dynamics. However, in reality, it may not be true for this extreme hour. Less heat could be delivered for this specific hour, which would cause a slight decrease in the comfort temperature. But this decrease in comfort temperature can be recovered by heating slightly more for the next hours. Overall, the maximum power required would be reduced, and unnecessary technologies may not have to be installed, which would lower drastically the TOTEX. However, considering temperature dynamics may overcomplexify the model. A nice trick would be to artificially change the few extreme weather data, while keeping the overall heat demand similar. This should provide more realistic results on the technologies to install and the TOTEX, but no information on the evolution of the comfort temperature could be retrieved. Buildings have a large temperature inertia. Not meeting totally the heat demand for a few hours would not cause a large temperature drop, but since the trick explained before cannot measure directly the effect on the comfort temperature, the method should be used very carefully, by computing temperature dynamics a posteriori.
