import numpy
import NR_functions as fct1
weather, buildings = fct1.load_data_weather_buildings()
# Generate the yearly occupancy profile of the buildings
occ_profile = fct1.occupancy_profile()

# Returns the annual profile of heat generated by people of a specified building
building_id = buildings.Name ## specifié nom bat
print(building_id)
heat_annual_people=fct1.people_gains(building_id, occ_profile)
